openapi: 3.0.1
info:
  title: '@jupiterone/graph-google'
  description: A JupiterOne managed integration for Google
  x-cortex-git:
    github:
      repository: JupiterOne/graph-google
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-google'
  x-cortex-service-groups:
    - tier-4
