name: J1 Integration deployment

on:
  release:
    types:
      - published

jobs:
  j1-integration-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Get version number
        id: get-version-number
        uses: actions/github-script@0.9.0
        with:
          script: |
            const tagName = context.payload.release.tag_name
            const versionNumber = tagName.replace("v", "")
            core.setOutput('versionNumber', versionNumber)
      - name: Bump integration deployment version
        id: create-pull-request
        uses: JupiterOne/integration-github-actions/create-integration-deployment@v1.2.2
        with:
          integrationName: google-workspace
          graphProjectName: google
          releaseNotes: ${{ github.event.release.body }}
          version: ${{ steps.get-version-number.outputs.versionNumber }}
          githubToken: ${{ secrets.AUTO_GITHUB_PAT_TOKEN }}
          npmAuthToken: ${{ secrets.NPM_AUTH_TOKEN }}
